application: campusmap-sd
version: 1
runtime: python
api_version: 1

handlers:
# for bulkloader
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /_debug
  script: debug.py
  login: admin

- url: /.*
  script: main.py

error_handlers:
- error_code: over_quota
  file: over_quota.html
